# CC = g++
# CFLAGS = -std=c++17
# LIBS = -lsfml-network -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system

# SRCS = main.cpp
# OBJS = $(SRCS:.cpp=.o)
# EXEC = file.exe

# .PHONY: all clean

# all: $(EXEC)

# $(EXEC): $(OBJS)
#     $(CC) $(OBJS) -o $(EXEC) $(LIBS)

# %.o: %.cpp
#     $(CC) $(CFLAGS) -c $< -o $@ -I/usr/local/include

# clean:
#     rm -f $(OBJS) $(EXEC)